// This file is auto-generated by scripts/sync-env.mjs.
// Loaded files: .env
export const environment = {
  "production": false,
  "mode": "test",
  "appName": "HRMN Soccer Data Provider",
  "apiUrl": "http://localhost:3000",
  "apiVersion": "v1",
  "variables": {
    "NG_APP_API_URL": "http://localhost:3000",
    "NG_APP_API_VERSION": "v1",
    "NG_APP_NAME": "HRMN Soccer Data Provider"
  }
} as const;
