// This file is auto-generated by scripts/sync-env.mjs.
// Loaded files: .env
export const environment = {
  "production": false,
  "appName": "HRMN Soccer Data Provider",
  "sportDbBaseUrl": "https://api.sportdb.dev",
  "sportDbApiKey": ""
} as const;
