import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import dotenv from 'dotenv';
import dotenvExpand from 'dotenv-expand';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');
const mode = process.argv[2] ?? 'development';

const loadOrder = [
  '.env',
  `.env.${mode}`,
  '.env.local',
  `.env.${mode}.local`,
];

const mergedVariables = {};
const loadedFiles = [];

for (const relativeFile of loadOrder) {
  const absoluteFile = path.join(rootDir, relativeFile);

  if (!fs.existsSync(absoluteFile)) {
    continue;
  }

  const parsed = dotenv.parse(fs.readFileSync(absoluteFile));
  const expanded = dotenvExpand.expand({
    parsed: { ...parsed },
    processEnv: { ...process.env, ...mergedVariables },
  }).parsed;

  Object.assign(mergedVariables, expanded);
  loadedFiles.push(relativeFile);
}

const publicVariables = Object.fromEntries(
  Object.entries(mergedVariables)
    .filter(([key]) => key.startsWith('NG_APP_'))
    .sort(([left], [right]) => left.localeCompare(right)),
);

const environmentDir = path.join(rootDir, 'src', 'environments');
const environmentFile = path.join(environmentDir, 'environment.ts');

const environmentObject = {
  production: mode === 'production',
  appName: publicVariables.NG_APP_NAME ?? 'HRMN Soccer Data Provider',
  sportDbBaseUrl:
    publicVariables.NG_APP_SPORTDB_BASE_URL ?? 'https://api.sportdb.dev',
  sportDbApiKey: publicVariables.NG_APP_SPORTDB_API_KEY ?? '',
};

const fileContents = `// This file is auto-generated by scripts/sync-env.mjs.\n` +
  `// Loaded files: ${loadedFiles.length > 0 ? loadedFiles.join(', ') : 'none'}\n` +
  `export const environment = ${JSON.stringify(environmentObject, null, 2)} as const;\n`;

fs.mkdirSync(environmentDir, { recursive: true });
fs.writeFileSync(environmentFile, fileContents);

console.log(`Generated src/environments/environment.ts for "${mode}" mode.`);